# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: ruby:2.3

cache:
  paths:
  - vendor
  - node_modules/

pages:
  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs npm
  - bundle install --path vendor
  - npm install
  - bundle exec middleman build
  artifacts:
    paths:
    - build
  only:
  - master
